# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:u9FjWIDroiYUmh1JtgWdPHmoAlTK4Vw4eMOfT2/DgM9U8JNfkgyOuJTeBxZZHeVtuYAPrc5Crdh9JrczePJFaHjsUcIwg1Uqvc9Q2xChLQcvYL6qeM4hJfFGDTqZfiV0Q5U9BdPuyZrLpsJEtlOa9VxaS9iRvVDglo5fUhhmQY7PwCSWUtreYX885fqzgzHjz5ZR6jR0q9iXMBLrGd2jI6xCOoUymcmAwXYtBlYuxzK3NCiZbA==,iv:/tDh9tnM8FWHyNFP6/fBBSouDS13C3vx5wr92bkHfjs=,tag:Q9nrz3vDvHZ0cy6NrJnG/A==,type:str]
sops:
  age:
    - recipient: age16cnyhpn9d6gg7nr6hg9wufgntragqqs924mtqv95tg2u4cf45essd47ue9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVL1lZM0dZOFVmdUlhZll6
        Wm5oZDYvSEEwbDc1dEIzTEp4Q2tSdGVtVkVZCkh4ekE2MG9DV3VBc0syTVU1Z0Vz
        d2p3MEVXN0xIQkFjdmQ5WkdNT04reGsKLS0tICtQbkNnaVFFUW0razI0SVVBTkJJ
        ZVJjaEM2RGdNVlg2ODJqQkxBR0xaWUEKLYOmfFCXIBeBbegwtbsBg4fNmgyPSVJn
        lzxrTpo0uSILQxnME+AKPxO+Ct/w7X2N/1xXGzbl+I2bsyBqrYRQpw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-13T14:20:27Z"
  mac: ENC[AES256_GCM,data:gPfWCJ/pba5zlyfSRs5gqaGquwvqGzGuvaPLKrcWEYL2gcb+n007GzmwppVaGsMOYcLIO/PgU/bn6o7DIpA1rLEJEhICd/G2Ob86O3lE0o51HF2YU0yDADl8ieSIOonKBDsOyoLS2DcbGHVmmiKXnIpzP9jEMiTPW5k9p2ArMQ8=,iv:twQy/up1/CsoNPUiaLwsm2q6zmEMnvJYRy1wjKjF4/4=,tag:wT0IpZMZgQ8WjDWL8vfwTQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
