# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:ECF+TlP06IXw5bb8ebqkuGKUk3wBss0avKuNA8NEkmktGW/ZClt4B5YG24Nj2B2tnarRUXuvcl0Q4Gr0mllyqyS6XGANL2lyiNK6Cu3+sXwzoXKwFHEEaDUq+6+KS6o+4PgOdCoCDALhs0mKxl2Qq4QnHPEBEfNs7xBhKZN1e2CJ4xlKrQ+gvEfpt4W4R70dDkifGj4fTCUh8h6eXgVcpsnNFOk4ppSsPYZy2VOHB97saHWXhQ==,iv:YzqRiuKHiYHBvV/7wkrww9w0Beyz6DIb3oJvrwV7TmY=,tag:Mzt/huc2bc4fS34kNJKVBA==,type:str]
sops:
  age:
    - recipient: age16cnyhpn9d6gg7nr6hg9wufgntragqqs924mtqv95tg2u4cf45essd47ue9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByQTFGVjk5di94NEZHWjkz
        dGIrbVJyQVVtVi9QZU81d2ZzSWJVYXJ2NG5jClpodU9XWjFBdFNEbUk5akZSa3px
        WFd6ZnZlRzhXemN5enczUlJneEJGV0kKLS0tIDFCdGlmZXJTd1JkcHNOVjEyZ3VM
        V2VqV0xvdVNlNm9ENFoxWE9naTdFTkUKBbKHqKEujIQjBrL7hMTxTbgElX0bN5G7
        ViatNHrKJMYUKgZxBJOTmjt2IAcMnBdmfFATcnuDzGbs1rFKJ/gW9A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-13T14:05:49Z"
  mac: ENC[AES256_GCM,data:kXMofAfMCfyPZmWUP5/YvQXZiRoXFjEVb2PCvJyY3nXxYwCUbL6J+z2OYgM+gCbad8tOvAjtYqTrz0xRMAPTcQyRZCpMWtsa80tYd2P1c+hEMOEcnLgQnhNxoB6rDvJ6zGJO5/xdoygp92x5T5IjU80a5z8YFodqJ9qRbB3nwV8=,iv:RFrYAO6nlpEXkBqMYV+njbovrB6TmXOqDcz535HLGPU=,tag:9c2TXKxXpEZevlfaBcuvQA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
