# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:tUbUTDIG2C0GGei3ZbalJtR6w++SVO7joMoJqP340nQlDM0ylNiaCKuFY1Xf5bzD+w7zufqB9AlqwX5O6Bbl1kBeF9uGHa2XWADLeZSLpfZ6+iON/qfVPBbTXjq2YVsgpcIuB8Cz7C1c729g/S+7F1THIuqUSqlqRC3RYinGXVNdC3R4U5X/7CC6LPXw1X6Ml/raXbRUpE9csc7/tyiaXnb1TrVscBgGaBxkZdNrmFZRHNVL3g==,iv:W5za4igGWY0wi8iB6uu7N8XlCo4czNdmzed1JdH+nD8=,tag:r0au8yClB0CU3sLz1vZ0Uw==,type:str]
sops:
  age:
    - recipient: age16cnyhpn9d6gg7nr6hg9wufgntragqqs924mtqv95tg2u4cf45essd47ue9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJU0dKMG1zb2lnNW9uT2tx
        VDcySnlYOHVsZlhqSjBLQWNNZU9QMDlQWndVCmpKNG9QNExLOUVyaDNwLzBKVTNk
        SEVVS1RIa1pncU9iSVpIQTdadFNZVjgKLS0tIGhWQnJ5ZWZ1aEY2cHA3azA1YXZu
        REtXdXIzVTlLMEVORnhNZjc1NHUyRDgKuX3oJpNIja4OS5rPIWCDGTMGQKVArBI3
        qMTRVIVEBINkCDarcVeRorT9qtSDHQj/rJ/e7reFanCEcPgNAD20kQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-14T14:30:19Z"
  mac: ENC[AES256_GCM,data:pqgMiY/tn1vk1MFRUL+tcDYNWbH8vWW4BtxsSvc1ERVuEnqY+hUWfM5NDXaPgx0GlORGRGsuhRRkmxr9o0gWRvKO9lEi6VgT8qYBfEN4NUUHIMzla6Czs03DSGylT8b2urVkFaC0axw5n3r2RqWA8uBr3U9B5gE+Wq0z6eD4YRU=,iv:7W5Dhu8iDna8IxWkt8GVprXdLARQ/nsQpb+dlwBUfsk=,tag:nl8J4xP8bIn0g5/oX12JZA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
