# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:3vvrbqdnXlHH9v6jNWlHOVq+PR5+/jMrxmTUfzUaXn7ooh9Oh6Nnpg==,iv:Vmg629FNLARZBxqL+X8xHiErVTZdW6NhYqJAWoky7Us=,tag:PR5F44gqwEAtbZsMNJdn8g==,type:str]
sops:
  age:
    - recipient: age16cnyhpn9d6gg7nr6hg9wufgntragqqs924mtqv95tg2u4cf45essd47ue9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIbDhBaFpMclk1Mk8vclo2
        SThVSmpleVFQbmJzR2lNM21wbDJRZy9xOXpzCnl1SXZRbUJBY3lDUk8zT0Z3Y3NC
        K1Y4ZXppTTA5K0wwYndQUHFpYTR5UDQKLS0tIGlpa0hzSGw3cGZjSDV4cGZ4azRT
        QUtGWEV3aVZqYXlHVVFPNmFFSzJKK3cKojzg5lw4xPQMHhhQnVuaGPLZtGhHpGL9
        vXb+UfPWbyo8Dv8k6xexvzpAz3O1lBvJiw3bRjV0RIrrIzpSTPRMKw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-13T14:20:27Z"
  mac: ENC[AES256_GCM,data:ONXtzI0sPTpr1W+R0UKZI6jTrdAYeIRZYn9fHC2Dq6spkCwx3x3gC9x49vCEeyBVbP2Gi+ELO9AeXjL/De63AJUoJzhxfVembXlRffHPFWMLAyEytiKcKbM5bsj8J0Ro1l3jnNTPOi1cznEg07ixIr7dyhBjwmzk/+Cx1pgOuZ8=,iv:zJDeF7s5Q848c/tDLf5DtvsgqtLd/AkqDVosqF9wbAY=,tag:RPx9/1JxoghRC0omjH81gA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
