# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:rzJWTxoRhg7HGFI3meQdgoJnrhFSZz7+ae5BUdoWaHt//EZLvIw8zw==,iv:JGeyrVwlixM2T62+TqkJsQtuLAbzmmilOjIH8H3TmUA=,tag:vq2mOOXVkinAlCrQNw6UcA==,type:str]
sops:
  age:
    - recipient: age16cnyhpn9d6gg7nr6hg9wufgntragqqs924mtqv95tg2u4cf45essd47ue9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzWmdmRE82RDE1RC9DWWtZ
        UXAranVDOXFEaTBGZnVKOVVmeWg3NzhmWlg0Ck1ZVGVUays2TWw1ZkVIU08vdGZk
        UURoVzZnbk03aWNRT21TSzJ1NFNaaTQKLS0tIGZWR2sxNy9icElzOEl0d2VvLzY0
        SHNreGVFTXpoNlJCR2gvV0s3MlY1bXcKJYoeB0RzJISHex+zHr0phfG9Djwg+/pM
        W6Hv0ruD0BufXvj2Pq1ry85lvqB+ksx7TXA1KRwkTh+RQBE9R8JDtA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-13T14:05:50Z"
  mac: ENC[AES256_GCM,data:nrgndwGwxNaedAplrR45gO7LgHn385C63UumIgaxG3FjAvYHUjyFTHaAZ6MjLSJl2BJz7Nk/7js1uKtpcn2I79/jPFgBBCyfl08NmJWdEQHq289/oSJRlrDKG+A0C+dfxl1aPLr7tA/TPdjdIiHXXFS6TfnvgThUFngjA4MxUgQ=,iv:qVQEJlxxAzRNIji2alj9W1vCvHnw4B4YMaMv2d43N2Y=,tag:oifH3fj+gtd42bCw+wQviQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
