# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:kH0JHVKZqmvn5dvO7CtojQEUJZfxYL3vFrJODc/fnKdT1be1N8F5Fw==,iv:mE8hw85gmBPFaDiFth9uOo0twl48oysGEbK4PSjvNvE=,tag:/j8juFM5uVjG2c1INDGVBw==,type:str]
sops:
  age:
    - recipient: age16cnyhpn9d6gg7nr6hg9wufgntragqqs924mtqv95tg2u4cf45essd47ue9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpYUtUQU54R0NwUzM2ZGJr
        aXE0bTBkcXRsNnByMDZhUmVFd1N2cHBEbzNjCmVUckFVWXlvOWU0eE1ERnREZktv
        RDhhWW9LRHBwSDFialpOVHRYM0FWeVkKLS0tIGdPc3lLN3dFMmZNNjFtNC90V2Vl
        a1phZW9jQ1VjaTd3Z0t0Qyt3WlJVME0KxR+Bi2LCCOPLLi+gvfo2Au9V84K4r08S
        2XCSJnh29rk19CRaaeYHnM4/jFvrle9Q1hpJm6pz7mUvXD7f/JcSRA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-14T14:30:19Z"
  mac: ENC[AES256_GCM,data:blqQhgTc9xxXZ/nA6PBG4as/GHKOBZ5XqGiPCg3dK6fUFyfcc4xzVqcOvJynUjoHqDAHXKBKVPr6mF3QJLE8PAka5sLpo1fOU6G0sg25ujPOBE0XwFL98GvRierJnH+hSKNWPzRFG+5vrBZiCqIMrVppU+gkZgXXpnYOahGuiFA=,iv:O+sVzxcy0toiwpt17IshaOw7nr9WG7WA0m6x5J5odlg=,tag:sY2NTaw+T3CVsOOozMSwJA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
