# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:6O16SoGoVYC47/FyBP51yHMokxwHEbAklO18CBWQHr0=,iv:SkXgDw3zb0U9ugrOXQiqJLHnBfpbyQsd2QBmpCmznBQ=,tag:xxuOF5IhOlAS1s6TaAiR+g==,type:str]
sops:
  age:
    - recipient: age16cnyhpn9d6gg7nr6hg9wufgntragqqs924mtqv95tg2u4cf45essd47ue9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5TG1WazFxL2x3aHJETm1R
        VHhWVEY4byt1M1RQVndEdGMxUDY5V1FWdlFrClA5QnpjazgrbEI4OENidVNmVXp0
        VlRucllnd2x6SjJDaUtlZ01aejhDaG8KLS0tICtZUDFKdlZKN1Y1T2dhSEZ1Q2xo
        LzZnT1RhdVIyZFpMdVdpMUxtR3hsYmcKew15AANOKfJ+q7nQjN866iF3sGx5xBD4
        N8bJsI3+i5tENA0SAK8+Bj/BF4GloqH7rIplw7S8XRDK+PfjWEMGZg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-11T13:25:06Z"
  mac: ENC[AES256_GCM,data:xdYCUqyz78b2gdK/NXeJxD1/d6gavxFHHW1/pHGcWoUj0sDpkoSAymz1QduaRuhuBNR75VKF6Txjg+NZC3eo59rOrmYEDDmg2lcimrmzs+W3sZ5nudLsRICljA+e5Ww8X3LtI2eBFM8tRAj4+BjgMi+K74Cf6Xf3k/gfH0sakYs=,iv:LjvJh+1C+hPt+Cs+IedbiLHed3Nw/OtkZ7cmxrCbU+4=,tag:emts6twqGvGw2iTAL9U9QQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
