# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:CxlpuiFfi6CRTqEDXSCewu/frsJimDQ8nBweW/ZbVSE=,iv:TRRUb4pjbApUczZpPq/0K7AHQ0iPujOjEdFDJh/EG9U=,tag:/NSAJslXV9jziILW4eQw1w==,type:str]
sops:
  age:
    - recipient: age16cnyhpn9d6gg7nr6hg9wufgntragqqs924mtqv95tg2u4cf45essd47ue9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFYlY4U1ZGaTRCU29ibUNl
        eXhEWUtWZHpJK0l6Ymw1dVY5VVhGWklQRW5JCmJSdCtjWU9DcHdFNGZLcElFVUpa
        RVJuWnNWeWdOczUvOEg1a3pybTEra2sKLS0tIEc4VEFOVXlMY0RYSTc3NmNaS3VQ
        KzBTUVZmM3lwVnFLZnBvS1NTYVFEVVEKKNiCQvR6b0ByUnAy/8DSG2zA5LpG9Np3
        g5exTBAa66ACIZOV+zcTI58PJEKwZGK33SpBfGQpD7N+4Qi4picYCw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-13T14:05:49Z"
  mac: ENC[AES256_GCM,data:hdTZo24PVSYJES7fkFa2576t7knV1OC4R2+HENwgW5uaqK4RwRB19aAXhCX0qu8bqlRw9UzpAlumhPlR91Ug7G/UI4i43jX/fvG2p495i6rivTC+4C+ONKOjdc6vkfHvlfJOTxddV9qcNLHaAvSzLIPCW245ihuM5Z83t67VBKY=,iv:8KVy4D4u5/Ph4yGm95m+5lnd8E4sGYk41MAZw4V/1jU=,tag:d9Qoplw4WTD8CcQmrBn7bA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
