# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:FO2ajT2VicLb16YgypHOJRv+0/DV7HBKj4r3aE1PbJA=,iv:dA+qU9Of5SNNJEWfuDKBaykN2U3+3nRjbg+Dy1am2AQ=,tag:7kiJdH48WlhMoZrTokfKUA==,type:str]
sops:
  age:
    - recipient: age16cnyhpn9d6gg7nr6hg9wufgntragqqs924mtqv95tg2u4cf45essd47ue9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVSHM2bk1ublEwQ0NETUR0
        WTFLY0hGS1c3WmVvZjlrZUxXckpvd1JvSGp3ClFZYU8reUFwSEpPRHh6ZENPTGk1
        VEl2b1h3cWhrUStYeGNwMjRDeVpRK3MKLS0tIEYwV1FuN1RMVFo0eWxpYmZraTJs
        ZWxrZnBhKzF0YU5CUVUxaEdnS0xSSVUKdsU9iGERxiaPsq/ZNk0Ii0pZsXeyPsas
        dInZMdGCgSs1APSbI+CT1iDJ66XqgXfS6150Rz+uKLG4rAkU7at+mg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-14T14:30:19Z"
  mac: ENC[AES256_GCM,data:7Rg1HtICTtuRIFYCMNPyESotRPGG84MNAjPI2AFc8da4mLeOIqW5hYKFPM1JXsCW0u+r7Sm3U1/1QFmdY94ulnalhVQDQLyCZ4q9QvxDGXg6A+fUWLxWV7o9kchAtqJ3uLxk9KDY8I7l6HXkjHR0svwBMfYE8FJ756uWc2OJF3I=,iv:B729qpHHm3UkSc21HWl8LIhYOX8VtsL352HmsDcY4kM=,tag:rGFEG+wVMzXztRwq7sgDsQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
