# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:Gwxcs5Xp0Ld0opz1Kk1luHP9oLV3mUyumvTx1zuI6Cq7GW3/YqpHvZEvJWhiAKw3j9u5aGVtxDfzad5EHwjxdpjTQzJgz9zkS4+VZ3GrIovTJSg2mnuf9vGoAe9JDqu8KNe3lCTEAH9qjbswPN3TzO4G0aF7AFS2Jh/4NwyR6zX8vBFSk9nY6bla3SiS5YFCPA1SBuqKX1qBB+V1WKT0dtnmCrW+wuVj60edQb8pYNXvibkX,iv:15mf/72WN6aVh8VYD/GEFclNdtjnCNkF47MNYM62+yE=,tag:EcJDXI38j0+lnok7RdPG4w==,type:str]
sops:
  age:
    - recipient: age10efx2c48psgle8unup397qar7p5edln9ym6v2jnf8w67xpjxr43sf8ulhq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0Q3dMRnVkd3BCMUNzNGVF
        ZU9FWERZS0FyclNtcWRsMzRMeElyNHhqdERVClZkUU1DdmVjdG9ydU5vWXhLbk9x
        eVV4dzZJR2tkOEhmOTRRdkVPOVR2dUEKLS0tIDlvL0cyYWY4akdSdW94RXRwZWx4
        SVRlYUdGUUkyYzlmODhYRWkzSXg1cTQKboYm4H6+BfWJHPF5dQKey5iQSHbmlIbc
        r1TmDbadu1wTDpU5m2nZ2AsHD58cWEWhYVPY1Bk3OG4ey6UMF1ncCQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-08-31T13:05:47Z"
  mac: ENC[AES256_GCM,data:xbctQwHIyCTasIj7aiG3rZbJ7V+vAi0ueAwQbrJlIC0a/3WJ2/hIpxvYyJdrd3O+HHdP7PfyaOnQuFM8VxRHuX5yCACqJl3l+3KxgKNcKR9FcmvhXP4dkiwWfhNlwBCJ91bIKIScYF/gqZ33RO0IOJH8YjC+ET7TG/yz0N4VsgY=,iv:Q2HjWYFVtebn6ki2MEDrVg33n2xyMJQ6inrnK6uYh6M=,tag:v0UTz3GA6T1ydV0eSFYGsQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
