apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:NBwL1cedT+GsCutf6Ug=,iv:2DZrUtQHyYeKV/UnPjPHGfaDe3XlPMs4iqkyRiL1OB8=,tag:xEaeDGyak9e46GA5XhUVVg==,type:str]
sops:
  age:
    - recipient: age16cnyhpn9d6gg7nr6hg9wufgntragqqs924mtqv95tg2u4cf45essd47ue9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByM1R0S0I3cHMwMmd0eUx0
        U0VnbVdMRSsxRlNwaTEzTGFaWUhwYktXUEd3CmdLQUo4MDE4dHpjSkh2ZjNNYjBI
        ZWlWSGZQNFZDWjJCRS9Cb0huWm5JSXMKLS0tIC9ialFISjU1U21HT2xWQ3dqaXND
        ZHVqQU9HS0x1Q3lPR0hYZ0xUMlZYVjQK5iV6r7Ypc/04xZCMl+PQDyKgAL6Cg8ZS
        9aeoNc71Db3W7GF+/QWK16MOpij45g2Bunw9cZpc26QTy0zY62zqMQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-13T14:05:50Z"
  mac: ENC[AES256_GCM,data:h7WCfJCg3aqDEKehCgCaqxxFRAA6UGva4kvHNtIBX0KxIEPvNQOjE4hYZFk1iqG2eqTExdDnZnyrOblggSvilwaJsSNDPk94IRhrJeDpv+a5f+cLGOMofiM6Bb8YLXQh5Is7JeJAxeU8QK+90Ij6k5BXPVg56w2iCKGCQQUO7D8=,iv:oucYYuNFh1FyEbwUR+Cj72mSrj8UsvbtgS9JKevyoKU=,tag:D4oTIwtdVeSzsXDwugtfFg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
