apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:uVuPo2oMv4M6OSOTINk=,iv:DViKTuCYPTZTmvoO2qR7cAFFNc6XRGRpyrW8zP17ebE=,tag:Vzg1ERqKeLsomV2v2CTr9Q==,type:str]
sops:
  age:
    - recipient: age16cnyhpn9d6gg7nr6hg9wufgntragqqs924mtqv95tg2u4cf45essd47ue9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqQWhaeDNGVVh6VWxJak53
        c21vT0R0REN0bk5sTUJrY2dUUWhJeE9MUm5jCmR4S0lGOWlSRW92TDNVWk4wT0ZG
        UzV4dFZ4YU1yS0NDRk1mam54NmZyR1kKLS0tIE5sQlE4dGtkMHg3QkdqZ1hFamF6
        UEd2ZUZvRytlblpHalgrNW9RaStxR1kK/QL+RaX2cpnkNaq6JFuFw+tQEdvLX9Q6
        8v4J40ep7PgivlN2auceXArdR49aCyVsNoxGr7QqtO/JURcTWWNZaA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-11T13:25:06Z"
  mac: ENC[AES256_GCM,data:9c+56obG0fMbHyLin9DnRKYsS+ryvnci0v3PppQ51XUEqocpUgZvIK1DfcM80M3PmCBXVB8Cjp+wE2zM2YouOJOpwd8msdG3DREXnaYoZ8lKa7ck6+hVbqo0aZKXhETb4WG5DQpPwrvspCJtVfzs6j7gLumXtXtqJaoSBy98QhM=,iv:GwuqlUaqLeqJRgyXvX7nMbiv/Tg5pYRlL3gj3GLePOY=,tag:w3CH4OHobCDR1dcrjrC/vw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
