apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:kbuzBfyK/YVZQX4u5NU=,iv:ae3+AgCjT5wWynDCHZACZJSLJOaUJXPdu4wwnDwLS/E=,tag:lu5BIkqEyhv/ndgOivWfCw==,type:str]
sops:
  age:
    - recipient: age16cnyhpn9d6gg7nr6hg9wufgntragqqs924mtqv95tg2u4cf45essd47ue9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQZHk1cWRHeWUzQXlCMm00
        TUE3akRXYnFVTElTZE9FQ1ZWS0NSbDZiYnhZCjlpL0dmQkNBaVFNdXB3eWxnd0pI
        K1pKV3BFWWwxczRXVmxpNFkwaWsvN1UKLS0tIEoxLzVJdzQyNWVBcXg1MGdaWGZ6
        M0FCUVg0R2xvWWtXRUEwdEE1Zml5cEkKQz54zC/EzIB3ltp6GwVy4AWfmPqyhRCu
        gCRMBx7A8KsTkcr0atjkQGi/3YUyg1YZp34Pc9O8XejWq/8J3R52tg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-14T14:30:19Z"
  mac: ENC[AES256_GCM,data:glAnkLdSgE6cfb8t6GgRsmzn//Qjw8sufrhC73XnUZ5kpI3wGhLo8JQUDarzauLsHQ2OA6BmANI7I1ZLIvpRHdJpH8BuIIDa1ew8nYziXPogeW+KP2nXLR3rXd4GVbE8Vkk9OsvEEU870htw0be3S0/MUKeuLmmGTORAXl/qtMo=,iv:vPh/tW5edrxT9vx3C1NPN2PpoH/Xv/KzK1wOqOdYuVQ=,tag:/Y/YBFSR/0sSde1CvCBv7Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
