apiVersion: v1
kind: Secret
metadata:
  name: sops-age
stringData:
  age.agekey: ENC[AES256_GCM,data:D0nk59VSyCPdqHrEmygPTsruSBeIgIY4KYi9Qi2gZaSibToqoad7/mJRtP65rgkV2XfRva3gX+pcXaJBntJAHC2F3a5P84v8RcQ=,iv:Vl6WBwbddUnfPTmrJIEl1IcGSYXu7t+c9LB2z3r+Pjw=,tag:94KhS7SaVas3aitRrhqTHw==,type:str]
sops:
  age:
    - recipient: age16cnyhpn9d6gg7nr6hg9wufgntragqqs924mtqv95tg2u4cf45essd47ue9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1SCtuQXVHVWVPMkhTRDdB
        RzczQ0NjcUNLTUx3R0JiM05XVWo1VDVRbFVJCjd4T05WT0EvaWVtQVpBY2lzcko3
        OWZTckhIV0tURDBncnQ5S1lYMi93VGsKLS0tIDRJN05JMTh6TmJjMVJERE0yT3VC
        TlRvNjNENkV5SDc3SHFHUHVkZVRhUzQKb7we4lhoTQTGlnKmr7rOjwugJo4j7L/P
        juS2G3MAoCkdQephQ3x5Rjs84XbWzzWI7DMAZRuwyASB9YuXo2r08g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-13T14:05:50Z"
  mac: ENC[AES256_GCM,data:gVvcGiSHxVy4q7Bs/cEi3JvBOjvix8GeEtR+Xq39jgk0aQ4SmH5RGJi+kJGKx6SoFrRO3L06T15/JFSh0eR3ozhgywdTFhlalAK1fTKI3m82SnCW5tinhSkREkvzH5Ob6VCpXCp5SdRriutM4JLCOUP+s7keVpFHvC641/P6gfc=,iv:jBxc1Wl+YuIurJtPFj/GwCHFyk2hmA+VGJ+1zlcoTPg=,tag:B5mCfegokfpUqINn9kodAw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
