# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:Lt6iXSFsTZQ+nuyoFdJNW90XjFRlmlWCEhyPdWL6GptLEMoBqrBhYg==,iv:Khf27C0R/VcvV8giSUoZixkXe3/WkRe88HlMDmsJck4=,tag:nSHIFO0gZGFtP3v8YJtCRw==,type:str]
sops:
  age:
    - recipient: age16cnyhpn9d6gg7nr6hg9wufgntragqqs924mtqv95tg2u4cf45essd47ue9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoT1ZOU2JNRlIvRC9EV2R6
        SWlDMnNpZXEvQlNjV3F1NU1KcnZxdUNwQjJnCktIZlpwMVBCZmVGSWlHVUNwUnA0
        eFNCdVdpdDFNZ2RpSnd4OXh5TXl2VHMKLS0tIGoyMXFsSGYwK2J0QzNrNUlEamRR
        SDJiekxoN3lIOVZKSkR5UVVZVE84dGsKUN+bA4K034vfrH97rrngT9ZEoVqEjd/s
        ftZpoHiQ5PizNTrkvyY7WzzoRP6biIHFpOgFliCWN+fyJzQhTIOZVQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-11T13:25:06Z"
  mac: ENC[AES256_GCM,data:IezfYHc5uKL0jUkLMpZVDqfoiNf3f4OYLVSxzXOYah3XteJ8G6K1z1CbAXSwfjG4ZmUbLrlB5BO1lB5Ffrzi+xjGS+cTITSSyEVsegJrMk5vz6j5J4e594k/ioWYjvPTr3RMg++gbCiUx0nE0cRbjGA/4/wbMqHgCVLb5LNOKAw=,iv:OKsZY+beb/kvUlJnHmMOxzJQWfcr5TDZc8pGukAL7iE=,tag:BBwIY1LLql5UqQ0Ks26WnQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
