# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:VFChiFtZlAc1vdBmhlJANK2xkYxyVCNZd7XUCHKMoN72N6nPU0LvpQ==,iv:IzfC9ff5DlMLAVJuO0ofaGPNVIZLpJHYOMEEx2xndys=,tag:IkIbxql7XyMQKB67xnToFg==,type:str]
sops:
  age:
    - recipient: age16cnyhpn9d6gg7nr6hg9wufgntragqqs924mtqv95tg2u4cf45essd47ue9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6eFlhZHFodUdTSHhNYXJq
        UXJOTFg0b3Z0RnU2VzNhQWlhSjZ5MUFOOGlBClhEYmoxOXhxRmlaMmM1MjdlcEs3
        YmI5ak1oMWl3RzFmL29EL3diZ1N6cFUKLS0tIG1wNXFpdlpjc3VSeWJ4b0ZsajBI
        K1BQVnJkWHhXcWtBdUNNby85VGVWS1EKe6GiaM7IP8Rm+hV3TkthHNNQHH67U+a9
        qlFGgEX1+cuX+YhqP7JpGWz62dnFRJWhZZexzDJRtgpuB5Zww7YAVg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-14T14:30:19Z"
  mac: ENC[AES256_GCM,data:uHY3RcEtll7xkjMhAp5NnWx2tswceWg5AAJBzhszLG75eUFV6l5lSCaHoSaNQMU3sLaSD8xkvUoUc2q9QKvwfEphVa6qTH9Em4ORPWiDRTEsjN4BrmPBj/28WMWsP3wR8jaj6y0PLEzTWFI0lxMIIxAHWYiUip2g7dNeRqP1tjA=,iv:O6wAQktymxsN26kLgNo5erf4sZYSLdLCLEZ+evaVWx0=,tag:3ie1kL/AFIsJaq+fekdf5w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
