# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:GjgeHE+leyO6QGNW/a55xgVZjMUW0edtc5SfPWDtz9WFAaYDaA3SIw==,iv:haySZgcMumr1TcUXdiVh9Gjjt7OUjmy1SuBSHeZIUNQ=,tag:Pwku13KPbXV/vKfhdzJKSg==,type:str]
sops:
  age:
    - recipient: age16cnyhpn9d6gg7nr6hg9wufgntragqqs924mtqv95tg2u4cf45essd47ue9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsTnppSHpaZlRPemN3VTFK
        UDBhdkluWmhCekxrNmQvQ0ZvWldiYjczaUVrCkdVR3lUTDNJWmlYdm8rTnk4R1hr
        WG1Rc1hPSUdSV2F4QUp6WkxPbnNTOEkKLS0tIFp6QjlrYzlTdDc2VW83djIwMEFB
        b0tNZ0Y4NnlkMXZMV01hUzA5bGVYa1EKxgNEylJQdnMvZrhFKCgxxKTlDDMuCBtY
        aU9xK94eFvic4oPRdh84NbcBuwfWJ4AS9Dn/VlqW4TLbsC4qhpuqhQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-13T14:20:27Z"
  mac: ENC[AES256_GCM,data:p76HLOgg6xP+TZlGvCHlyvbXvEIrU3vtsulNCivKjW4kAmypeMgOjnGoj5BBS+hP9Zey6E6fFgjoVYxF+BYRBDwYa7wzwl3bFA/lzCXaUDQBglyap3sy57ZDHQQrQF1PMkuS0omTBRBb+yuPK0XTP2GT8HBOcJELWIk4Rp8WY+g=,iv:Ub37AutOaS2EdUpXRJxpT/UZgiPqi4g4ZFMgIcezIKU=,tag:cBYJN0nu4UQoTxZbS1hhPw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
